### ISSUE TITLE
TypeError: draw_networkx_nodes() got an unexpected keyword argument 'figure'

### ISSUE THREAD

**Issue by caffery-chen** [Telecominfraproject/oopt-gnpy#391] opened 2021-05-01 14:26 UTC
**Describe the bug**
gnpy-transmisson-example --plot
got following error:

line 29, in plot_baseline
    plot = draw_networkx_nodes(network, nodelist=network.nodes(), node_color='#ababab', **kwargs)
TypeError: draw_networkx_nodes() got an unexpected keyword argument 'figure'

**To Reproduce**
gnpy-transmisson-example --plot

**Comment by ojnas** [comment] 2021-05-02 14:13
Thanks for reporting, I can confirm the bug. The cause is an API change in NetworkX 2.5 (they stopped silently ignoring unused keywords: https://github.com/networkx/networkx/pull/4033). NetworkX 2.5 was released in Aug 2020 so it seems not many are using this --plot feature since nobody reported it before. Fix is waiting here:

https://review.gerrithub.io/c/Telecominfraproject/oopt-gnpy/+/515675

**Closed** 2021-05-03 12:58 UTC
Labels: bug
