### ISSUE TITLE
novel update with tx_osnr feature fails with automatic mode selection

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#185] opened 2018-12-19 15:02 UTC
**Describe the bug**
when no mode is indicated, the automatic mode selection fails
python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2.xls -o tototo 
Traceback (most recent call last):
  File "path_requests_run.py", line 307, in <module>
    rqs = requests_from_json(data, equipment)
  File "path_requests_run.py", line 111, in requests_from_json
    requests_list.append(Path_request(**params))
  File "/home/user/workspace/TIP/gnpy/gnpy/core/request.py", line 42, in __init__
    params = RequestParams(**params)
TypeError: __new__() missing 1 required positional argument: 'tx_osnr'

I will propose a correction today + tests to avoid future problems.

**Comment by jeanluc-auge** [comment] 2019-01-14 17:23
I have an alternate proposal:
-this slows the code down
-the path calculation is no longer transponder agnostic
-we will have the same issue with ROADM noise contribution
Instead I propose to add the transponder Rx OSNR (and ROADM add/drop by the way) contribution at the end of the calculation with just an OSNR sum. I have checked, it gives the same result. This small ase contribution will not make any difference in the nli calculation anyway, so it doesn't matter if we had it at the end of the path. This way it can be added when chosing the transponder and you don't need ot re-run the simulation for every transponder mode.

**Comment by ojnas** [comment] 2019-01-16 07:48
@jeanluc-auge 

Your proposal to add tx_osnr contribution at the end in order to speed up calculation is what I had in mind in my comment here: https://github.com/Telecominfraproject/oopt-gnpy/pull/186#issuecomment-448991213.

On the other hand I don't really agree with this argument:
>-the path calculation is no longer transponder agnostic

The path calculation already depends on baud_rate (and it may also depend on roll_off when Raman is included) so it's not really transponder agnostic anyway.

I proposed an alternative way to speed up calculation by caching results in my comment here: https://github.com/Telecominfraproject/oopt-gnpy/pull/186#issuecomment-453526197. I don't have a strong opinion on which of the proposals is better but somehow it feels less "future proof" to add noise contributions at the end. Even if it gives the same result now there is no guarantee that this will be the case for new network element models.

**Comment by ggrammel** [comment] 2019-01-29 15:34
```
python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2.xls -o tototo
```
creates the following output:
```
N channels =  95
N channels =  95
N channels =  95
could not find tsp : vendorA_trx-type1 with mode: PS_SP64_2 in eqpt library
Computation stopped.
```
However ```eqpt_config.json``` has the Transceiver type included

**Comment by ojnas** [comment] 2019-01-29 15:45
@ggrammel Your issue seems like a duplicate of #149 but this should be fixed in develop branch.

**Comment by EstherLerouzic** [comment] 2019-01-29 16:05
I think that this issue (on automatic ode selection) is now solved, I suggest to close the issue

**Comment by dutc** [comment] 2019-01-29 16:33
I cannot reproduce the bug that @ggrammel reports above using the following command-line:
`$ python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2.xls`

@ggrammel, can you provide the output of the following commands:

```
$ git rev-parse --abbrev-ref HEAD
develop
$ git rev-parse HEAD
ec20d3981b126fa6ff68b71588bc898b1d6e72c3
$ python -c 'import inspect; import gnpy; print(inspect.getfile(gnpy))'
/path/to/gnpy/__init__.py
```

**Comment by ggrammel** [comment] 2019-01-30 20:00
above test was accidentally performed on current master
on develop:
```python path_requests_run.py meshTopologyExampleV2.xls meshTopologyExampleV2.xls -o tototo```
creates the expected output.

**Closed** 2019-01-30 20:33 UTC
Labels: bug
