### ISSUE TITLE
Plot feature does not display correct positions

### ISSUE THREAD

**Issue by EstherLerouzic** [Telecominfraproject/oopt-gnpy#202] opened 2019-01-29 16:17 UTC
**Describe the bug**
Except for the base example (single EDFA) the plot feature shows a star-like set of links all sharing the same vertex, which makes the feature useless.

**Comment by dutc** [comment] 2019-01-29 16:21
Is this the case even when lat, long information is provided?

**Comment by ojnas** [comment] 2019-01-29 16:31
I think this is related to #170.

**Comment by EstherLerouzic** [comment] 2019-01-29 16:32
I think so, I tested on "python transmission_main_example.py CORONET_Global_Topology.xls" where I did not change any thing and on other files as well. It seems that there is an additionnal point added in all edges, but I could not figure out where this is coming from

**Comment by dutc** [comment] 2019-01-29 16:40
I'm going to close this as a duplicate of #170

**Closed by dutc** 2019-01-29 16:40 UTC
Labels: bug, duplicate
